name: analyzed_angular_plugin_loader
version: 0.0.0
description: Temp means of loading angular analysis into an angular project.
environment:
  sdk: '>=1.24.0-dev.1.0'
dependencies:
  angular_analysis_plugin: '0.0.8'
dev_dependencies:
dependency_overrides:
  angular_analysis_plugin:
    path: /home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/angular_analysis_plugin
  analysis_server:
    path: /home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/deps/sdk/pkg/analysis_server
  analyzer:
    path: /home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/deps/sdk/pkg/analyzer
  front_end:
    path: /home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/deps/sdk/pkg/front_end
  analyzer_plugin:
    path: /home/mfairhurst/dart/ng-analyzer-with-sdk-at-HEAD/deps/sdk/pkg/analyzer_plugin
